### HTML Endpoints
GET http://127.0.0.1:3000/

###

### API Endpoints
GET http://127.0.0.1:3000/api/pets


###
POST http://127.0.0.1:3000/api/pets
Content-Type: application/json

{
    "name": "Mr. Pete",
    "pic": "assets/images/bp-lot-1-siamese-color-outdoor.png",
    "breed": "Kitty",
    "type": "Cat",
    "sex": "Male",
    "color": "White",
    "sprayedNeutered": "Yes",
    "age": "8",
    "id": "23648905",
    "microchipNumber": "562039485-33405",
    "datePosted": "2025-04-03",
    "status": [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchiped"
    ],
    "bio": "Say hello to Mr. Pete, a chatty and affectionate Siamese cat with striking blue eyes. Oliver loves to follow his humans around the house and 'talk' to them with his signature meows. He enjoys puzzle toys, warm sunspots, and cuddling under blankets. Oliver does best in a home where he gets plenty of attention and interaction."
}

###

GET http://127.0.0.1:3000/api/pets/?type=dog

###


GET http://127.0.0.1:3000/api/pets/?type=cat

###

### Get pet by id
GET http://127.0.0.1:3000/api/pets/76238

###
GET http://127.0.0.1:3000/api/pets/

###

PUT http://127.0.0.1:3000/api/pets/23648905
Content-Type: application/json

{
    "name": "Mr. Pete2",
    "pic": "assets/images/bp-lot-1-siamese-color-outdoor.png",
    "breed": "Kitty",
    "type": "Cat",
    "sex": "Male",
    "color": "White",
    "sprayedNeutered": "Yes",
    "age": "8",
    "id": "23648905",
    "microchipNumber": "562039485-33405",
    "datePosted": "2025-04-03",
    "status": [
      "Health checked",
      "Vaccinations up to date",
      "Regularly dewormed",
      "Microchiped"
    ],
    "bio": "Say hello to Mr. Pete, a chatty and affectionate Siamese cat with striking blue eyes. Oliver loves to follow his humans around the house and 'talk' to them with his signature meows. He enjoys puzzle toys, warm sunspots, and cuddling under blankets. Oliver does best in a home where he gets plenty of attention and interaction."
}


###

DELETE http://127.0.0.1:3000/api/pets/23648905


###
PUT http://127.0.0.1:3000/api/pets/:id
Content-Type: application/json